name: generate-test-db-dispatch
on:
  workflow_dispatch:

jobs:
  generate-database:
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dojoengine/dojo:v1.2.2
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Start Katana
        run: |
          mkdir -p /tmp/katana_db
          katana --db-dir /tmp/katana_db --chain tests/fixtures/test-chain &
          # Give some time for Katana to start
          sleep 5

      - name: Clone Dojo repository
        uses: actions/checkout@v4
        with:
          repository: dojoengine/dojo
          path: ./dojo

      - name: Build and migrate example project
        working-directory: ./dojo/examples/spawn-and-move
        run: |
          sozo build
          sozo migrate --account-address 0x1f401c745d3dba9b9da11921d1fb006c96f571e9039a0ece3f3b0dc14f04c3d --private-key 0x7230b49615d175307d580c33d6fda61fc7b9aec91df0f5c1a5ebe3b8cbfee02

      - name: Compress database
        run: |
          mkdir -p fixtures
          tar -czvf fixtures/katana_db.tar.gz -C /tmp katana_db

      - id: version_info
        run: |
          DATE=$(date +%Y%m%d%H%M%S)
          echo "version=db-update-${DATE}" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.CREATE_PR_TOKEN }}
          add-paths: |
            fixtures/katana_db.tar.gz
          title: "Update test database: ${{ steps.version_info.outputs.version }}"
          commit-message: "Update test database from Dojo project: ${{ steps.version_info.outputs.version }}"
          branch: db-update-${{ steps.version_info.outputs.version }}
          base: main
          delete-branch: true
